version: '3.7'
services:
  discovery-pg-db:
    image: postgres:13
    container_name: discovery-pg-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: discovery-db
