version: "3.8"

services:
  db:
    image: postgres:13
    container_name: discovery-pg-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -h ${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
  discovery-api:
    container_name: discovery-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
      # - 9229:9229  Debug port
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
volumes:
  pgdata-dev:
